In [73]:
%matplotlib inline

In [74]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

outlier_circle = dict(markerfacecolor='#081d58', marker='.')
meanlineprops = dict(linestyle='--', linewidth=2, color='#7fcdbb')
medianprops = dict(linestyle='dotted', linewidth=2, color='#1d91c0')
boxprops=dict(facecolor='#ffffd9', color='#ffffd9')

## Importing data


In [75]:
required_df = pd.read_csv("/Users/jxxt/verzeo/Information.csv",engine='python')

In [76]:
required_df.head()

_unit_id  _golden _unit_state  _trusted_judgments _last_judgment_at  \
0  815719226    False   finalized                   3    10/26/15 23:24   
1  815719227    False   finalized                   3    10/26/15 23:30   
2  815719228    False   finalized                   3    10/26/15 23:33   
3  815719229    False   finalized                   3    10/26/15 23:10   
4  815719230    False   finalized                   3     10/27/15 1:15   

   gender  gender:confidence profile_yn  profile_yn:confidence  \
0    male             1.0000        yes                    1.0   
1    male             1.0000        yes                    1.0   
2    male             0.6625        yes                    1.0   
3    male             1.0000        yes                    1.0   
4  female             1.0000        yes                    1.0   

          created  ...                                       profileimage  \
0    12/5/13 1:48  ...  https://pbs.twimg.com/profile_images/414342229...   
1   10/1/12 13:51  ...  https://pbs.twimg.com/profile_images/539604221...   
2  11/28/14 11:30  ...  https://pbs.twimg.com/profile_images/657330418...   
3   6/11/09 22:39  ...  https://pbs.twimg.com/profile_images/259703936...   
4   4/16/14 13:23  ...  https://pbs.twimg.com/profile_images/564094871...   

   retweet_count sidebar_color  \
0              0        FFFFFF   
1              0        C0DEED   
2              1        C0DEED   
3              0        C0DEED   
4              0             0   

                                                text tweet_coord tweet_count  \
0  Robbie E Responds To Critics After Win Against...         NaN      110964   
1  ���It felt like they were my friends and I was...         NaN        7471   
2  i absolutely adore when louis starts the songs...         NaN        5617   
3  Hi @JordanSpieth - Looking at the url - do you...         NaN        1693   
4  Watching Neighbours on Sky+ catching up with t...         NaN       31462   

    tweet_created      tweet_id   tweet_location               user_timezone  
0  10/26/15 12:40  6.587300e+17  main; @Kan1shk3                     Chennai  
1  10/26/15 12:40  6.587300e+17              NaN  Eastern Time (US & Canada)  
2  10/26/15 12:40  6.587300e+17           clcncl                    Belgrade  
3  10/26/15 12:40  6.587300e+17    Palo Alto, CA  Pacific Time (US & Canada)  
4  10/26/15 12:40  6.587300e+17              NaN                         NaN  

[5 rows x 26 columns]

In [77]:
required_df.shape

(20050, 26)

In [78]:
required_df.columns

Index(['_unit_id', '_golden', '_unit_state', '_trusted_judgments',
       '_last_judgment_at', 'gender', 'gender:confidence', 'profile_yn',
       'profile_yn:confidence', 'created', 'description', 'fav_number',
       'gender_gold', 'link_color', 'name', 'profile_yn_gold', 'profileimage',
       'retweet_count', 'sidebar_color', 'text', 'tweet_coord', 'tweet_count',
       'tweet_created', 'tweet_id', 'tweet_location', 'user_timezone'],
      dtype='object')

In [81]:
required_df.columns = required_df.columns.str.strip().str.replace('_', ' ')

In [82]:
required_df.columns

Index([' unit id', ' golden', ' unit state', ' trusted judgments',
       ' last judgment at', 'gender', 'gender:confidence', 'profile yn',
       'profile yn:confidence', 'created', 'description', 'fav number',
       'gender gold', 'link color', 'name', 'profile yn gold', 'profileimage',
       'retweet count', 'sidebar color', 'text', 'tweet coord', 'tweet count',
       'tweet created', 'tweet id', 'tweet location', 'user timezone'],
      dtype='object')

In [85]:
required_df.columns = required_df.columns.str.strip().str.replace(' ', '_')
required_df.columns

Index(['unit_id', 'golden', 'unit_state', 'trusted_judgments',
       'last_judgment_at', 'gender', 'gender:confidence', 'profile_yn',
       'profile_yn:confidence', 'created', 'description', 'fav_number',
       'gender_gold', 'link_color', 'name', 'profile_yn_gold', 'profileimage',
       'retweet_count', 'sidebar_color', 'text', 'tweet_coord', 'tweet_count',
       'tweet_created', 'tweet_id', 'tweet_location', 'user_timezone'],
      dtype='object')

In [86]:
required_df['golden'].unique()

array([False,  True])

In [87]:
required_df['unit_state'].unique()

array(['finalized', 'golden'], dtype=object)

In [88]:
required_df['trusted_judgments'].unique()

array([  3, 249, 271, 245, 261, 247, 242, 256, 262, 259, 264, 258, 260,
       228, 233, 255, 235, 254, 231, 274, 246, 273, 239, 270, 237, 227,
       253, 252, 212, 240, 248, 250])

In [89]:
required_df['profile_yn'].unique()

array(['yes', 'no'], dtype=object)

In [90]:
required_df['gender_gold'].unique()

array([nan, 'male', 'brand', 'female', 'female\nunknown', 'male\nunknown',
       'unknown'], dtype=object)

In [91]:
required_df['profile_yn_gold'].unique()

array([nan, 'yes'], dtype=object)